BINS := ab_mult acker count_primes palin puzzle vetrec 

all: $(BINS)

ab_mult: ab_mult.c

acker: acker.c

count_primes: count_primes.c

palin: palin.c    

puzzle: puzzle.c  

vetrec: vetrec.c

# trash is the var that contains files to be removed in ../Makefile
trash += $(BINS)

include ../Makefile
